[package]
name = "axum-example"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 子模块依赖
common = {path = "../common"}
axum = "0.7.3"
tokio = { version = "1", features = ["full"] }
